/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2017-06-06 13:39:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import metier.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t\t<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t\t<title>Ma page</title>\n");
      out.write("\t\t<style>\n");
      out.write("\t\t\t.redbann{\n");
      out.write("\t\t\t\tbackground-color: red;\n");
      out.write("\t\t\t\tcolor:#fff;\n");
      out.write("\t\t\t\ttext-align:center;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\t<body >\n");
      out.write("\n");
      out.write("\t\n");
      out.write("<!-- \n");
      out.write("\tA) Recuperation du panier ( et creation le cas écheant ) \n");
      out.write("-->\t\n");
 
	
		Panier myPanier;	
		int prixTT=0;

		if(session.getAttribute("pan")==null){
			myPanier=new Panier();
		}else{
			myPanier=(Panier)session.getAttribute("pan");
		}

/*
<!-- 
	B) Recuperation du paramètre si il existe et ajout au panier + redirection ci dessous 
-->
*/
		String tmp;
		int i=0;
		int taille=myPanier.getNbArticle();
		
		while(i<taille){

			if(request.getParameter("take"+i)!=null&&(tmp=request.getParameter("id"+i))!=null){
				if(myPanier.getCount(tmp)==null)
					myPanier.addPanier(tmp,Integer.parseInt(request.getParameter("qte"+i)));
				else
					myPanier.addPanier(tmp,myPanier.getCount(tmp)+Integer.parseInt(request.getParameter("qte"+i)));

					session.setAttribute("pan",myPanier);
			}
			else if((tmp=request.getParameter("id"+i))==null){
				i=100;
			}

			i++;
		}
		

      out.write("\n");
      out.write("<!--\n");
      out.write("\t A) Recuperation du panier ( et creation le cas écheant ) ci dessus \n");
      out.write("-->\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t<h2 class=\"redbann\"> Votre panier : <a href=\"index.jsp?clear=yes\">clear</a></h2>\n");
      out.write("\n");
      out.write("\t\t<table class=\"table\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>Libelle</th><th>Quantité</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("<!-- \n");
      out.write("\tC ) affichage du panier avec libelles ci dessous\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t");
      out.print(myPanier.toString());
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<form method=\"get\" action=\"/servlet/Commander\">\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Valider\"/>\n");
      out.write("\t\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<h2 class=\"redbann\">Les articles proposés sont : </h2>\n");
      out.write("\t\t\n");
      out.write("\t\t<table class=\"table\">\n");
      out.write("\t\t\t<tr>\t\t\n");
      out.write("\t\t\t\t<th>Libelle</th><th>Prix</th><th> Qte </th> <th> Acheter </th>\n");
      out.write("\t\t\t<tr/>\n");
      out.write("\n");
 
	Connection con = null;

		try{

		    Class.forName("org.postgresql.Driver");
			String url = "jdbc:postgresql://psqlserv/n2p1";
			String nom = "barbetf";
			String mdp = "moi";
			con = DriverManager.getConnection(url,nom,mdp);

			Statement stmt = con.createStatement();
			stmt = con.createStatement();

			String query = "select lib,prix,reference from article";
			ResultSet rs = stmt.executeQuery(query);

      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<form method=\"get\" action=\"index.jsp\">\n");

			 i=0;
			while(rs.next()){

      out.write("\t\t\n");
      out.write("<!-- \n");
      out.write("\tD) affichage du panier avec libelles \n");
      out.write("-->\t\t\t\n");
      out.write("\t\t\t<tr>\n");
				out.println("<input type=\"hidden\" value=\""+rs.getString("reference")+"\" name=\"id"+i+"\"/> ");

      out.write("\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString("lib"));
      out.write("</td><td>");
      out.print(rs.getString("prix"));
      out.write("</td>\n");

				out.println("<td><input type=\"number\" name=\"qte"+i+"\" value=\"\" class=\"form-control\"/></td>");
				out.println("<td><input type=\"checkbox\" name=\"take"+i+"\" value=\"ok\" /></td>");

      out.write("\t\n");
      out.write("\t\t</tr>\n");
      out.write("\n");

			i++;
			}

      out.write("\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Acheter\" class=\"btn btn-default\"/>\n");
      out.write("\t\t\t</form>\n");

		session.setAttribute("taille",i);
		}catch (Exception e) {

      out.write(" <h1>Oups ! ( ");
      out.print( e.getMessage() );
      out.write(" )</h1> ");

		}
		finally {	  
			try{
				con.close();	  
			}catch (Exception e) {

      out.write("<h1>Oups ! (");
      out.print( e.getMessage() );
      out.write(")</h1>");

			}
		}
if(request.getParameter("clear")!=null){
			session.invalidate();
			response.sendRedirect("../tpcontrol/index.jsp");
		
		}

      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t\t\n");
      out.write("\t\t<a href=\"index.jsp?clear=yes\" class=\"btn\">remise à zero</a>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
